development_sqlite:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  database: iboflavin_development
  host: localhost
  username: iboflavin
  password: hap5ut8och
  encoding: utf8
  socket: /tmp/mysql.sock
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: iboflavin_production
  host: localhost
  username: iboflavin
  password: hap5ut8och
  encoding: utf8
  socket: /tmp/mysql.sock
