development:
  adapter: postgresql
  database: iboflavin_development
  host: localhost
  username: iboflavin
  password: hap5ut8och
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: iboflavin_production
  host: localhost
  username: iboflavin
  password: hap5ut8och
  encoding: utf8
